apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    app: jenkins-server
    env: test
    tier: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: web-server
  template:
    metadata:
      name: jenkins
      labels:
        tier: web-server
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:alpine
        ports:
        - containerPort: 8080